// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7buner41PZZ00is4QRQmrHgtADzbDda0',
    appId: '1:844333518208:web:26103364d513c205d44565',
    messagingSenderId: '844333518208',
    projectId: 'flutter-hotel-app-4d455',
    authDomain: 'flutter-hotel-app-4d455.firebaseapp.com',
    storageBucket: 'flutter-hotel-app-4d455.appspot.com',
    measurementId: 'G-CTYHR11SPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9AofK7Km7sESFt9hPX5aXdJIVusLH434',
    appId: '1:844333518208:android:098631b5e1266e4ed44565',
    messagingSenderId: '844333518208',
    projectId: 'flutter-hotel-app-4d455',
    storageBucket: 'flutter-hotel-app-4d455.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAja7n7haCFah4LYeb3DdFfZDU28ZRN5uk',
    appId: '1:844333518208:ios:b615e826aa489c05d44565',
    messagingSenderId: '844333518208',
    projectId: 'flutter-hotel-app-4d455',
    storageBucket: 'flutter-hotel-app-4d455.appspot.com',
    iosClientId: '844333518208-v7a2oofma2v5kviggjes4r4nmkenjfgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAja7n7haCFah4LYeb3DdFfZDU28ZRN5uk',
    appId: '1:844333518208:ios:b615e826aa489c05d44565',
    messagingSenderId: '844333518208',
    projectId: 'flutter-hotel-app-4d455',
    storageBucket: 'flutter-hotel-app-4d455.appspot.com',
    iosClientId: '844333518208-v7a2oofma2v5kviggjes4r4nmkenjfgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelApp',
  );
}
